### PR TITLE
Ensure a valid background image value

### LINKED ISSUE #147: Ensure graceful handling of invalid / missing background image in theme
Splitting out as an issue from #144:

example of what a missing file does:
```
Error: Cannot find module './bg-045.svg'.
.svg:54
The above error occurred in the <ThemeBackgroundPicker> component:
    in ThemeBackgroundPicker (created by OnClickOutside(ThemeBackgroundPicker))
    in OnClickOutside(ThemeBackgroundPicker) (created by AppComponent)
    in div (created by AppComponent)
    in section (created by BrowserPreview)
    in div (created by BrowserPreview)
    in BrowserPreview (created by AppComponent)
    in main (created by AppComponent)
    in div (created by AppComponent)
    in AppComponent (created by Connect(AppComponent))
    in Connect(AppComponent)
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
react-dom.development.js:9747
Error: Cannot find module './bg-045.svg'.
.svg:54
```

### PR DESCRIPTION
**Pull request by lmorchard**
Fixes #147

### CODE REVIEW

File: src/lib/themes.js [hunk 1]
```diff
@@ -38,21 +47,21 @@ export const normalizeTheme = (data = {}) => {
   const theme = {
     colors: normalizeThemeColors(data.colors, defaultTheme.colors),
     images: {
-      additional_backgrounds: []
+      additional_backgrounds: [ "" ]
```
Comment (pdehaan) [inline src/lib/themes.js]: Why an empty string instead of just an empty array?

File: src/lib/themes.js [hunk 2]
```diff
@@ -38,21 +47,21 @@ export const normalizeTheme = (data = {}) => {
...
   };
   const images = data.images ? data.images : {};
   if (images.headerURL) {
-    theme.images.additional_backgrounds = [ images.headerURL ];
+    theme.images.additional_backgrounds = [ normalizeThemeBackground(images.headerURL) ];
   }
   if (images.additional_backgrounds) {
-    theme.images.additional_backgrounds = images.additional_backgrounds;
+    theme.images.additional_backgrounds = [
+      normalizeThemeBackground(images.additional_backgrounds[0])
```
Comment (pdehaan) [inline src/lib/themes.js]: So even though `additional_backgrounds` is an array, it will always have a maximum of 1 element, correct?
Is that because of a limitation in the front end UI? Or, something more interesting?

Comment (lmorchard) [reply src/lib/themes.js]: The theme API can layer multiple backgrounds, but we're only using one in this project for now

File: src/lib/themes.js (hunk 1 above)
Comment (lmorchard) [reply src/lib/themes.js]: Wanted to ensure there's always a 0 element that's defined

**Comment by johngruen** [comment]
This looks great...should we do an add-on bump with this since i think we should deploy this fix to dev

**Comment by lmorchard** [comment]
Good call! Just added another commit to bump the version

File: src/lib/themes.js (hunk 1 above)
Comment (chuckharmston) [reply src/lib/themes.js]: How does Firefox handle this
